version: '3.7'

services:
  redis:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - "6379:6379"

  nginx:
    network_mode: host
    image: nginx:alpine
    restart: always
    # ports:
    #   - "4000:80"
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

